alias ..='cd ..'
alias ...='cd ../..'
alias md='mkdir -p'
alias lf="yazi"
alias slf="sudo -E yazi"
alias tx="tmux"
alias re="source ~/.zshrc && exec zsh"
alias lz="lazygit"
alias fd='fd -H'
alias clear-clipboard='cliphist wipe'
alias v="nvim"
alias vim="nvim"
alias svim="sudo -E nvim"
alias k="kubectl"
alias kx="kubectx"
alias kns="kubens"
alias fz="fzf --preview-window=hidden"
alias t='go-task'
alias task='go-task'
alias ap='ansible-playbook'
alias av='ansible-vault'
alias tf='terraform'
alias vg='vagrant'
alias c='clear'
alias oc='opencode'
alias list-files-extension="fd -t f | sed -n 's/.*\.\([^.\/]*\)$/\1/p' | sort | uniq -c | sort -rn"
alias h="helm"
alias send-to-phone='kdeconnect-cli -d "$(kdeconnect-cli -a --id-only)" --share'
alias dd='echo "Use --> caligula - https://github.com/ifd3f/caligula"'
alias cat="bat"
alias p='pacman'
alias py="python3"
alias d="docker"
alias di="docker image"
alias dpsa="docker ps -a"
alias de="docker exec"
alias dc="docker compose"
alias dn="docker network"
alias dv="docker volume"
alias rm='echo "This is a dangerous command. Use trash instead."'
alias cp='rsync --archive --verbose --human-readable --progress --itemize-changes --stats'
alias ls="eza --icons -a -l --time-style relative --changed"
alias l="eza --icons -a -l --time-style relative --changed"
alias lg="eza --icons -a -l --time-style relative --changed -g"
alias g='git'
alias ga='git add'
alias gcl='git clone'
alias gf='git fetch'
alias gfo='git fetch origin'
alias gm='git merge'
alias gl='git pull'
alias gp='git push'
alias gr='git remote'
alias gst='git status'
alias uncommit="git reset HEAD~1"             # Undo the last commit, keep changes staged
alias recommit="git commit --amend --no-edit" # Amend last commit without changing message
alias editcommit="git commit --amend"         # Amend last commit and edit message
alias undocommit="git reset --soft HEAD~1"    # Undo last commit, keep changes staged
