alias ..='cd ..'
alias ...='cd ../..'
alias md='mkdir -p'
alias lf="yazi"
alias slf="sudo -E yazi"
alias tx="tmux"
alias re="source ~/.zshrc && exec zsh"
alias lz="lazygit"
alias fd='fd -H'
alias v="nvim"
alias vim="nvim"
alias svim="sudo -E nvim"
alias k="kubectl"
alias kx="kubectx"
alias kns="kubens"
alias fz="fzf --preview-window=hidden"
alias t='go-task'
alias task='go-task'
alias ap='ansible-playbook'
alias av='ansible-vault'
alias tf='terraform'
alias vg='vagrant'
alias c='clear'
alias oc='opencode'
alias h="helm"
alias dd='echo "Use --> caligula - https://github.com/ifd3f/caligula"'
alias cat="bat"
alias py="python3"
alias d="docker"
alias rm='echo "This is a dangerous command. Use trash instead."'
alias cp='rsync --archive --verbose --human-readable --progress --itemize-changes --stats'
alias ls="eza --icons -a -l --time-style relative --changed"
alias l="eza --icons -a -l --time-style relative --changed"
alias lg="eza --icons -a -l --time-style relative --changed -g"
alias g='git'
alias uncommit="git reset HEAD~1"             # Undo the last commit, keep changes staged
alias recommit="git commit --amend --no-edit" # Amend last commit without changing message
alias editcommit="git commit --amend"         # Amend last commit and edit message
alias undocommit="git reset --soft HEAD~1"    # Undo last commit, keep changes staged
